# ไฟล์ docker-compose.yml สำหรับระบบที่ใช้ Docker Swarm

services:
  # กำหนดบริการชื่อ web
  web:
    # ระบุอิมเมจที่ใช้สำหรับบริการนี้
    image: boomgt123/test_swarm01:2.0
    
    # กำหนดพอร์ตที่เปิดให้บริการ (พอร์ต 3000 บนเครื่อง host ไปยังพอร์ต 3000 ในคอนเทนเนอร์)
    ports:
      - "3000:3000"

    healthcheck:
      # คำสั่งที่ใช้ตรวจสอบว่า service ทำงานปกติหรือไม่
      # ["CMD", "curl", "-f", "http://localhost:3000/"] หมายถึง ใช้คำสั่ง curl เรียกไปที่ URL ภายใน container
      # -f คือ flag ที่ทำให้ curl คืนค่าผิดพลาด (exit code ไม่เป็น 0) เมื่อเซิร์ฟเวอร์คืนค่า HTTP error (4xx, 5xx)
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      # ระยะเวลาที่จะตรวจสอบซ้ำ - ทุกๆ 10 วินาที Docker จะเรียกใช้คำสั่งตรวจสอบ
      interval: 10s
      # เวลาสูงสุดที่ยอมรับได้ในการรอผลการตรวจสอบ
      # หากคำสั่งใช้เวลานานเกิน 5 วินาที จะถือว่าเช็คล้มเหลว
      timeout: 5s
      # จำนวนครั้งที่ยอมให้ตรวจสอบล้มเหลวติดต่อกัน
      # หากล้มเหลว 3 ครั้งติดกัน จะถือว่า container ไม่สามารถใช้งานได้ (unhealthy)
      # และ Swarm จะพิจารณาปรับสถานะหรือรีสตาร์ทตามนโยบายที่กำหนด
      retries: 3
      # ระยะเวลาผ่อนผันตั้งแต่ container เริ่มทำงาน จนกว่าจะเริ่มการตรวจสอบ
      # ให้เวลา container บูตและเริ่มแอปพลิเคชันให้พร้อมก่อน 10 วินาที
      start_period: 10s
    
    # ส่วนการกำหนดค่าสำหรับการเผยแพร่บริการใน Swarm
    deploy:
      # จำนวนสำเนา (คอนเทนเนอร์) ที่ต้องการให้รันพร้อมกัน
      replicas: 3
      
      # กำหนดให้รันเฉพาะบน worker nodes เท่านั้น ไม่รันบน manager
      placement:
        constraints:
          - node.role != manager  # เงื่อนไขไม่ให้รันบนโหนดที่เป็น manager
      
      # การกำหนดค่าสำหรับการอัปเดต (Rolling Update)
      update_config:
        parallelism: 1  # อัปเดตครั้งละ 1 คอนเทนเนอร์
        delay: 10s  # รอ 10 วินาทีก่อนอัปเดตคอนเทนเนอร์ถัดไป
      
      # นโยบายการรีสตาร์ทเมื่อเกิดปัญหา
      restart_policy:
        condition: on-failure  # รีสตาร์ทเฉพาะเมื่อเกิดความล้มเหลว
        max_attempts: 3  # พยายามรีสตาร์ทสูงสุด 3 ครั้ง
    
    # กำหนดเครือข่ายที่คอนเทนเนอร์นี้จะเชื่อมต่อ
    networks:
      - webnet

# กำหนดเครือข่ายที่ใช้ในระบบ
networks:
  # เครือข่ายชื่อ webnet
  webnet:
    # ใช้ไดรเวอร์แบบ overlay ซึ่งเหมาะสำหรับการสื่อสารระหว่างโหนดใน Swarm
    driver: overlay